# Generated by Django 4.1.3 on 2022-12-15 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Admin", "ADMIN"),
                            ("Reader", "READER"),
                            ("Reporter", "REPORTER"),
                        ],
                        default="Reader",
                        max_length=25,
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Middle Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non-binary", "Non-binary"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Contact Number",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos",
                        verbose_name="User Photo",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Permanent Address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=250)),
                ("contact", models.CharField(max_length=25)),
                ("image", models.ImageField(upload_to="photos")),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("bronz", "Bronz"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date_time", models.DateTimeField()),
                ("end_date_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=1000, verbose_name="Title")),
                (
                    "sub_title",
                    models.CharField(max_length=1000, verbose_name="Sub Title"),
                ),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos", verbose_name="Images"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos", verbose_name="Images"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos", verbose_name="Images"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Reporting"),
                            ("agency", "News Agency"),
                        ],
                        max_length=100,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sports", "Sports"),
                            ("politics", "Politics"),
                            ("finance", "Finance"),
                            ("international", "International"),
                        ],
                        max_length=100,
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("edit_date", models.DateTimeField(auto_now=True)),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False, verbose_name="Report Anonymously?"
                    ),
                ),
                ("view_count", models.BigIntegerField(default=0)),
                ("coin_generated", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ReaderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReporterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "press_id",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos",
                        verbose_name="Press ID",
                    ),
                ),
                (
                    "identity_document",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos",
                        verbose_name="Identity Document",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="photos")),
                ("file1", models.FileField(upload_to="documents")),
                (
                    "file2",
                    models.FileField(blank=True, null=True, upload_to="documents"),
                ),
                (
                    "news_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.news",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reader",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("news_portal.portaluser",),
        ),
        migrations.CreateModel(
            name="Reporter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("news_portal.portaluser",),
        ),
        migrations.CreateModel(
            name="RewardGranted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins_redeemed", models.CharField(max_length=25)),
                ("monetary_value", models.CharField(max_length=25)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.reporter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportedNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("denied", "Denied"),
                            ("accepted", "Accepted"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "news_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.news",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.reader",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="news",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="news_portal.reporter"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "news_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.news",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.reader",
                    ),
                ),
            ],
        ),
    ]
