# Generated by Django 4.1.3 on 2022-12-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="coin_generated",
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="RewardGranted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins_redeemed", models.CharField(max_length=25)),
                ("monetary_value", models.CharField(max_length=25)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.reporter",
                    ),
                ),
            ],
        ),
    ]
