# Generated by Django 4.1.3 on 2022-12-05 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news_portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=250)),
                ("contact", models.CharField(max_length=25)),
                ("image", models.ImageField(upload_to="")),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("bronz", "Bronz"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date_time", models.DateTimeField()),
                ("end_date_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("sub_title", models.CharField(max_length=1000)),
                ("description", models.TextField()),
                ("body", models.TextField()),
                ("image1", models.ImageField(upload_to="")),
                ("image2", models.ImageField(upload_to="")),
                ("image3", models.ImageField(upload_to="")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Reporting"),
                            ("agency", "News Agency"),
                        ],
                        max_length=100,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sports", "Sports"),
                            ("politics", "Politics"),
                            ("finance", "Finance"),
                            ("international", "International"),
                        ],
                        max_length=100,
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("edit_date", models.DateTimeField(auto_now=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("view_count", models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="portaluser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non-binary", "Non-binary"),
                ],
                max_length=20,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.CreateModel(
            name="ReportedNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=50)),
                (
                    "news_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.news",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.reader",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("file", models.FileField(upload_to="")),
                (
                    "news_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.news",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "news_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.news",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_portal.reader",
                    ),
                ),
            ],
        ),
    ]
