# Generated by Django 4.1.3 on 2022-12-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_portal", "0002_alter_portaluser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="portaluser",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
