# Generated by Django 4.1.3 on 2022-12-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_portal", "0003_alter_news_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="body",
            field=models.TextField(verbose_name="Body"),
        ),
        migrations.AlterField(
            model_name="news",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos", verbose_name="Images"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos", verbose_name="Images"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos", verbose_name="Images"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="is_anonymous",
            field=models.BooleanField(
                default=False, verbose_name="Report Anonymously?"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="sub_title",
            field=models.CharField(max_length=1000, verbose_name="Sub Title"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=1000, verbose_name="Title"),
        ),
    ]
