# Generated by Django 4.1.3 on 2022-12-16 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("news_portal", "0003_portaluser_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardgranted",
            name="date_redeemed",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portaluser",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Address"
            ),
        ),
    ]
