# Generated by Django 4.1.3 on 2022-12-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_portal", "0004_rewardgranted_date_redeemed_alter_portaluser_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardgranted",
            name="coins_redeemed",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="rewardgranted",
            name="monetary_value",
            field=models.BigIntegerField(),
        ),
    ]
