# Generated by Django 4.1.3 on 2022-12-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_portal", "0005_alter_rewardgranted_coins_redeemed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardgranted",
            name="monetary_value",
            field=models.FloatField(),
        ),
    ]
